export default {
  aaMath: {
    avatar: 'logos/awc-400x400.jpeg',
    description: 'Graduated with a 3.5 GPA.',
    institution: 'Arizona Western College',
    src: 'certs/aa-mathematics.jpg',
    title: 'Associate of Arts in Mathematics',
    type: 'img',
    year: '2020',
  },
  amatycResearch: {
    avatar: 'logos/amatyc-1050x500.png',
    description: 'Our team recieved 2nd place in the AMATYC Student Research League.',
    institution: 'AMATYC',
    src: 'certs/amatyc-research-award.jpg',
    title: 'Second Place Certificate of Recognition',
    type: 'img',
    year: '2019',
  },
  asCS: {
    avatar: 'logos/awc-400x400.jpeg',
    description: 'Graduated with a 3.5 GPA.',
    institution: 'Arizona Western College',
    src: 'certs/as-computer-science.jpg',
    title: 'Associate of Science in Computer Science',
    type: 'img',
    year: '2020',
  },
  asEngineering: {
    avatar: 'logos/awc-400x400.jpeg',
    description: 'Graduated with a 3.5 GPA.',
    institution: 'Arizona Western College',
    src: 'certs/as-engineering.jpg',
    title: 'Associate of Science in Engineering',
    type: 'img',
    year: '2020',
  },
  asPhysics: {
    avatar: 'logos/awc-400x400.jpeg',
    description: 'Graduated with a 3.5 GPA.',
    institution: 'Arizona Western College',
    src: 'certs/as-physics.jpg',
    title: 'Associate of Science in Physics',
    type: 'img',
    year: '2020',
  },
  hackerRankJava: {
    avatar: 'logos/hackerrank-800x800.png',
    institution: 'HackerRank',
    src: 'https://www.hackerrank.com/certificates/iframe/c6f24474b302',
    title: 'Java (Basic) Certificate',
    type: 'iframe',
    year: '2020',
  },
  hackerRankJS: {
    avatar: 'logos/hackerrank-800x800.png',
    institution: 'HackerRank',
    src: 'https://www.hackerrank.com/certificates/iframe/b09d78fe952e',
    title: 'JavaScript (Basic) Certificate',
    type: 'iframe',
    year: '2020',
  },
  hsDiploma: {
    avatar: '',
    description: 'Graduated Chapin High School with a 4.2 GPA and a high school major in Mathematics.',
    institution: 'Chapin High School',
    src: 'certs/hs-diploma.jpg',
    title: 'High School Diploma',
    type: 'img',
    year: '2015'
  },
  informaticsCert: {
    avatar: 'logos/awc-400x400.jpeg',
    description: '3.5 GPA',
    institution: 'Arizona Western College',
    src: 'certs/informatics-cert.jpg',
    title: 'Certificate of Informatics Software Development and Information Management',
    type: 'img',
    year: '2020',
  },
  juliaCert: {
    avatar: 'logos/julia-900x900.jpeg',
    description: 'While tutoring a Computer Science student in South Africa, I studied Julia to build a program simulating the Dijkstra\'s algorithm.',
    institution: 'JuliaAcademy',
    src: 'certs/julia-cert.pdf',
    title: 'Certificate of Completion for Introduction to Julia (for programmers)',
    type: 'iframe',
    year: '2020',
  },
  neo4jCypherFund: {
    avatar: 'neo4j-2048x2048.png',
    institution: 'Neo4j GraphAcademy',
    src: 'https://graphacademy.neo4j.com/c/c2d6b475-cc3d-4215-a16e-ec6907f6d35d/',
    title: 'Cypher Fundamentals Course Completion',
    type: 'iframe',
    year: '2023',
  },
  neo4jGraphDataModelingFund: {
    avatar: 'neo4j-2048x2048.png',
    institution: 'Neo4j GraphAcademy',
    src: 'https://graphacademy.neo4j.com/c/2dd6f1cd-f5a8-4564-b4ea-1fcd8576bc1b/',
    title: 'Graph Data Modeling Fundamentals Course Completion',
    type: 'iframe',
    year: '2023',
  },
  neo4jImportingCSVData: {
    avatar: 'neo4j-2048x2048.png',
    institution: 'Neo4j GraphAcademy',
    src: 'https://graphacademy.neo4j.com/c/164b4477-aa6a-495b-9c6f-5d4434e6cfd7/',
    title: 'Importing CSV Data into Neo4j Course Completion',
    type: 'iframe',
    year: '2023',
  },
  neo4jIntroNeo4jGraphDS: {
    avatar: 'neo4j-2048x2048.png',
    institution: 'Neo4j GraphAcademy',
    src: 'https://graphacademy.neo4j.com/c/6e2562ff-5174-49c0-b194-79465792d46e/',
    title: 'Introduction to Neo4j Graph Data Science Course Completion',
    type: 'iframe',
    year: '2023',
  },
  neo4jFundamentals: {
    avatar: 'neo4j-2048x2048.png',
    institution: 'Neo4j GraphAcademy',
    src: 'https://graphacademy.neo4j.com/c/86793db0-3130-4cf0-aaca-9bd76eb2651d/',
    title: 'Neo4j Fundamentals Course Completion',
    type: 'iframe',
    year: '2023',
  },
  neo4jGraphDataScienceCert: {
    avatar: 'neo4j-2048x2048.png',
    institution: 'Neo4j GraphAcademy',
    src: 'https://graphacademy.neo4j.com/c/0d9bc660-e382-4334-a437-0301b3f96de8/',
    title: 'Neo4j Graph Data Science Certification',
    type: 'iframe',
    year: '2023',
  },
  neo4jGraphDataScienceFund: {
    avatar: 'neo4j-2048x2048.png',
    institution: 'Neo4j GraphAcademy',
    src: 'https://graphacademy.neo4j.com/c/8fdfa24d-0a9c-4e80-862e-6d60ab5b2668/',
    title: 'Neo4j Graph Data Science Fundamentals Course Completion',
    type: 'iframe',
    year: '2023',
  },
  sololearnCpp: {
    avatar: 'logos/sololearn-1670x1670.png',
    institution: 'Sololearn',
    src: 'certs/sololearn-cpp.pdf',
    title: 'Course Certificate in C++',
    type: 'iframe',
    year: '2020',
  },
  sololearnCSS: {
    avatar: 'logos/sololearn-1670x1670.png',
    institution: 'Sololearn',
    src: 'certs/sololearn-css.pdf',
    title: 'Course Certificate in CSS',
    type: 'iframe',
    year: '2020',
  },
  sololearnHTML: {
    avatar: 'logos/sololearn-1670x1670.png',
    institution: 'Sololearn',
    src: 'certs/sololearn-html.pdf',
    title: 'Course Certificate in HTML',
    type: 'iframe',
    year: '2020',
  },
  sololearnJava: {
    avatar: 'logos/sololearn-1670x1670.png',
    institution: 'Sololearn',
    src: 'certs/sololearn-java.pdf',
    title: 'Course Certificate in Java',
    type: 'iframe',
    year: '2020',
  },
  sololearnJS: {
    avatar: 'logos/sololearn-1670x1670.png',
    institution: 'Sololearn',
    src: 'certs/sololearn-js.pdf',
    title: 'Course Certificate in JavaScript',
    type: 'iframe',
    year: '2020',
  },
  sololearnReactRedux: {
    avatar: 'logos/sololearn-1670x1670.png',
    institution: 'Sololearn',
    src: 'certs/sololearn-react-redux.pdf',
    title: 'Course Certificate in React + Redux',
    type: 'iframe',
    year: '2020',
  },
  sololearnSQL: {
    avatar: 'logos/sololearn-1670x1670.png',
    institution: 'Sololearn',
    src: 'certs/sololearn-sql.pdf',
    title: 'Course Certificate in SQL',
    type: 'iframe',
    year: '2020',
  },

}